package grammar;

/**
 * Partial implementation of a function.
 * Its intended use is to be implemented by functions that need to handle their
 * parameters in special manners.
 * Since most of the special functions will be autogenerated, the user can
 * specify the probability of a Special Function to be chosen once it's been
 * randomly selected. This is specially useful when a type contains few functions
 * and the chances of selecting a special function are larger than it's desired.
 * 
 * @author Jesús Irais González Romero
 */
public abstract class SpecialFunction extends Function {

    
    protected double probability;

    /**
     * @return The probability of this special function to be chosen once it's
     * been randomly selected.
     */
    public double getProbability() {
        return this.probability;
    }

    @Override
    public Class<?>[] getParameterTypes() {
        return this.parameterTypes;
    }

    @Override
    public String getName() {
        return this.name;
    }
}